
front=GATCGGAAGAGCACACGTCTGAACTCCAGTCAC
end=ATCTCGTATGCCGTCTTCTGCTTG

#zgrep -o -e "${front}......${end}" $*

zcat $* | sed -n 's/.*GATCGGAAGAGCACACGTCTGAACTCCAGTCAC\(......\)ATCTCGTATGCCGTCTTCTGCTTG.*/\1/p'
